### ISSUE TITLE
Issues getting input from the command line

### ISSUE THREAD

**Issue by jcsansom-cyber** [comp426-2022-spring/a02#1]
Hi there! I keep having issues with getting input from the command line. When I try using minimist I keep getting:
jcsansom@jaycees-air a02-jcsansom-cyber % node flips.js number=3
file:///Users/jcsansom/Documents/comp426/a02-jcsansom-cyber/flips.js:2
const args = require("minimist")(process.argv.slice(2))
             ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/jcsansom/Documents/comp426/a02-jcsansom-cyber/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/jcsansom/Documents/comp426/a02-jcsansom-cyber/flips.js:2:14
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
And I've tried doing it other ways but it will only take the default.

**Comment by jcsansom-cyber** [comment]
Nevermind I figured it out

**Comment by samrshi** [comment]
Recommended in office hours: check out the bottom of w03 on the course website: [https://comp426.johndmart.in/w/03/#esm-and-commonjs-issues](https://comp426.johndmart.in/w/03/#esm-and-commonjs-issues)
