### ISSUE TITLE
Tests Fail with Seemingly Right Output

### ISSUE THREAD

**Issue by cgoldman123** [comp426-2022-spring/a02#12]
Hi Professor

It seems as if my code isn’t passing the autograder's tests even though the output looks right. I’ve attached a screenshot for the results of running flips with no argument (node flips.js) and flips with a random argument i.e. 10 (node flips.js --number=10). Please let me know if this is an autograder issue or something I need to fix. 

<img width="539" alt="Screen Shot 2022-02-16 at 10 40 27 PM" src="https://user-images.githubusercontent.com/59986682/154401127-cf0ad3b3-7bab-4f1c-b5e2-38c688166bcd.png">
Thank you!

**Comment by turner-white** [comment]
I was having the same problem until I checked another post where they suggested to make it so that when the count of heads or tails is 0, the function doesn't return it as part of the object. So for your no argument version, try returning just { heads: 1 }. That worked for me

**Comment by camsimba** [comment]
Hey @cgoldman123, it looks like the autograder is having an issue with the output of your flips and I think it might have something to do with the default value you give to the number within flips.js. Try taking `process.env.number` out on line 12. I'm not sure if this will help, but it doesn't hurt to try.

Let me know if neither this nor @turner-white's approach doesn't work and we can work on it some more!

**Comment by cgoldman123** [comment]
Hey @turner-white and @camsimba thanks for the help! Taking out the headCount when heads was 0 and tailCount when tails was 0 did it for me.
