### ISSUE TITLE
Autograder does not pass for seemingly valid inputs

### ISSUE THREAD

**Issue by Gauravmrao** [comp426-2022-spring/a02#15]
the last test of the autograder does not pass for me in github, but with inputs in my terminal everything seems to work fine.

**Comment by samrshi** [comment]
look into using mininist for command line parsing. this will allow us to include the param labels in our commands `node count-flips --call=heads` instead of `node count-flips heads`

**Comment by samrshi** [comment]
hint: check out the bottom of [w03](https://comp426.johndmart.in/w/03/) for advice on a problem you'll run into
