### ISSUE TITLE
Require minimist to take in command line inputs creates conflicts

### ISSUE THREAD

**Issue by ceciliallee** [comp426-2022-spring/a02#2]
I am trying to use minimist to take in command line inputs, but it says that "require is not defined". I look it up and it says it's because in the json file, we have the type as "module" and the syntax should be "import", but importing minimist doesn't do anything. 

```
const args = require('minimst')(process.argv.slice(2));
```
Are we supposed to use something else to get command line inputs?

**Comment by smelliskay** [comment]
Hi! There was an earlier issue which was dealing with something similar. Try checking out the bottom of w03 on the course website. Here is the link. https://comp426.johndmart.in/w/03/#esm-and-commonjs-issues
module.createRequire() should be your friend here. :)

**Comment by ceciliallee** [comment]
I just tried it, but I get another error that says `minimist.createRequire is not a function`. Is this the right syntax for it? ```const args = minimist.createRequire('minimist')(process.argv.slice(2))```

**Comment by smelliskay** [comment]
Your original code actually isn't incorrect, you just need to do some fiddling around beforehand. You need to import createRequire first, and then set a const require = createRequire with the proper argument. There is no such thing (to my knowledge) as minimist.createRequire. 

Sorry if this answer is confusing but I'm trying not to give away exactly what your code should look like in an effort to encourage you to continue seeking answers through provided documentation. If you get too frustrated or something remains confusing, don't hesitate to drop by in office hours.

**Comment by ceciliallee** [comment]
After looking at the documentation more, I tried importing create Require from minimist and also making the const require, but it is saying `SyntaxError: Named export 'createRequire' not found. The requested module 'minimist' is a CommonJS module, which may not support all module.exports as named exports.`.

**Comment by smelliskay** [comment]
Solved in office hours: remember to follow node's documentation for module.createRequire very literally!
