### ISSUE TITLE
Different Laundry Lists

### ISSUE THREAD

**Issue by franqfzh** [comp426-2022-spring/a02#3]
The coin.mjs file in a02 wants us to do countFlips and flipACoin but a02 assignment page wants us to do guess a flip instead. I wonder which instruction should I follow?

**Comment by samrshi** [comment]
Looking at the project writeup, it looks like you should do both. You should write and export all of the functions in `coin.mjs` and use them when writing your scripts. Does that make sense?

**Comment by franqfzh** [comment]
Thank you. That make sense.

**Comment by camsimba** [comment]
I'll close this thread but if you have any other questions feel free to make a new issue or reopen it!
